# 'version' 속성 없음 (Compose v2)
services:
  sfu-server:
    build: ./sfu-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - coturn
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - sfu-server
  coturn:
    image: instrumentisto/coturn
    restart: always
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    environment:
      - TURN_SECRET=supersecret
    command: >
      --lt-cred-mech --no-cli --no-tls --no-dtls --user testuser:testpass --realm=webrtc.local --external-ip=${PUBLIC_IP}
