apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-sender-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-sender-a
  template:
    metadata:
      labels:
        app: webrtc-sender-a
    spec:
      containers:
      - name: webrtc-sender-a
        image: webrtcsfu.azurecr.io/webrtc-sender-a:latest
        ports:
        - containerPort: 5175
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_SENDER_ROLE
          value: "A"
        - name: VITE_PORT
          value: "5175"
        - name: VITE_TURN_SERVER
          value: "20.214.122.119:3478"
        - name: VITE_TURN_USERNAME
          value: "testuser"
        - name: VITE_TURN_CREDENTIAL
          value: "testpass" 
        - name: VITE_SFU_SERVER
          value: "20.249.161.77"
        - name: VITE_APP_VERSION
          value: "1.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-sender-a
spec:
  type: LoadBalancer
  ports:
  - port: 5175
    targetPort: 5175
  selector:
    app: webrtc-sender-a
