apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-frontend
  template:
    metadata:
      labels:
        app: webrtc-frontend
    spec:
      containers:
      - name: webrtc-frontend
        image: webrtcsfu.azurecr.io/webrtc-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_PORT
          value: "5173"
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 5173
    targetPort: 5173
  selector:
    app: webrtc-frontend
